"""Type stub for the compiled ``objectfile._objectfile`` extension module."""

from __future__ import annotations

import collections.abc
import enum
import os
import pathlib

# The enums below are pyo3 native enums. They behave like integer enums
# (members compare equal to their ordinal); they are declared here as IntEnum
# for type-checking purposes.

class Format(enum.IntEnum):
    Unknown = ...
    Coff = ...
    Elf = ...
    MachO = ...
    Pe = ...
    Wasm = ...
    Xcoff = ...

class Architecture(enum.IntEnum):
    Unknown = ...
    Aarch64 = ...
    Aarch64_Ilp32 = ...
    Alpha = ...
    Arm = ...
    Avr = ...
    Bpf = ...
    Csky = ...
    E2K32 = ...
    E2K64 = ...
    I386 = ...
    X86_64 = ...
    X86_64_X32 = ...
    Hexagon = ...
    Hppa = ...
    Ia64 = ...
    LoongArch32 = ...
    LoongArch64 = ...
    M68k = ...
    Mips = ...
    Mips64 = ...
    Mips64_N32 = ...
    Msp430 = ...
    PowerPc = ...
    PowerPc64 = ...
    Riscv32 = ...
    Riscv64 = ...
    S390x = ...
    Sbf = ...
    Sharc = ...
    Sparc = ...
    Sparc32Plus = ...
    Sparc64 = ...
    SuperH = ...
    Wasm32 = ...
    Wasm64 = ...
    Xtensa = ...

class Endianness(enum.IntEnum):
    Little = ...
    Big = ...

class ObjectKind(enum.IntEnum):
    Unknown = ...
    Relocatable = ...
    Executable = ...
    Dynamic = ...
    Core = ...

class SymbolKind(enum.IntEnum):
    Unknown = ...
    Text = ...
    Data = ...
    Section = ...
    File = ...
    Label = ...
    Tls = ...

class SymbolScope(enum.IntEnum):
    Unknown = ...
    Compilation = ...
    Linkage = ...
    Dynamic = ...

class LinkKind(enum.IntEnum):
    Unknown = ...
    Relocatable = ...
    Executable = ...
    PieExecutable = ...
    SharedLibrary = ...
    Core = ...

class SymbolHash(enum.IntEnum):
    Unknown = ...
    Absent = ...
    SysV = ...
    GNU = ...
    Both = ...

class Import:
    def __init__(
        self,
        name: str | None = None,
        ordinal: int | None = None,
        library: str | None = None,
        is_weak: bool = False,
    ) -> None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def ordinal(self) -> int | None: ...
    @property
    def library(self) -> str | None: ...
    @property
    def is_weak(self) -> bool: ...
    def __lt__(self, other: Import) -> bool: ...

class Export:
    def __init__(
        self,
        name: str | None = None,
        ordinal: int | None = None,
        address: int | None = None,
        is_weak: bool = False,
        version: str | None = None,
        version_hidden: bool = False,
    ) -> None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def ordinal(self) -> int | None: ...
    @property
    def address(self) -> int | None: ...
    @property
    def is_weak(self) -> bool: ...
    @property
    def version(self) -> str | None: ...
    @property
    def version_hidden(self) -> bool: ...
    def __lt__(self, other: Export) -> bool: ...

class Symbol:
    def __init__(
        self,
        name: str | None = None,
        address: int = 0,
        size: int = 0,
        kind: SymbolKind = ...,
        scope: SymbolScope = ...,
        is_undefined: bool = False,
        is_global: bool = False,
        is_weak: bool = False,
        section_index: int | None = None,
        version: str | None = None,
        version_hidden: bool = False,
    ) -> None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def address(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def kind(self) -> SymbolKind: ...
    @property
    def scope(self) -> SymbolScope: ...
    @property
    def is_undefined(self) -> bool: ...
    @property
    def is_global(self) -> bool: ...
    @property
    def is_weak(self) -> bool: ...
    @property
    def section_index(self) -> int | None: ...
    @property
    def version(self) -> str | None: ...
    @property
    def version_hidden(self) -> bool: ...
    def __lt__(self, other: Symbol) -> bool: ...

class ImportIter:
    def __iter__(self) -> ImportIter: ...
    def __next__(self) -> Import: ...

class ExportIter:
    def __iter__(self) -> ExportIter: ...
    def __next__(self) -> Export: ...

class LibraryIter:
    def __iter__(self) -> LibraryIter: ...
    def __next__(self) -> str: ...

class SymbolIter:
    def __iter__(self) -> SymbolIter: ...
    def __next__(self) -> Symbol: ...

class ObjectFile:
    @property
    def path(self) -> pathlib.Path | None: ...
    @property
    def format(self) -> Format: ...
    @property
    def architecture(self) -> Architecture: ...
    @property
    def is_64(self) -> bool: ...
    @property
    def endianness(self) -> Endianness: ...
    @property
    def kind(self) -> ObjectKind: ...
    @property
    def link_kind(self) -> LinkKind: ...
    @property
    def soname(self) -> str | None: ...
    @property
    def interpreter(self) -> str | None: ...
    @property
    def symbol_hash(self) -> SymbolHash: ...
    def rpaths(self) -> list[str]: ...
    def runpaths(self) -> list[str]: ...
    def provided_versions(self) -> list[str]: ...
    def required_versions(self) -> dict[str, list[str]]: ...
    def imports(self) -> ImportIter: ...
    def exports(self) -> ExportIter: ...
    def libraries(self) -> LibraryIter: ...
    def symbols(self) -> SymbolIter: ...
    def dynamic_symbols(self) -> SymbolIter: ...
    def gpu_code_objects(self) -> list[GpuCodeObject]: ...
    def gpu_targets(self) -> list[str]: ...

class GpuCodeObject:
    @property
    def compute_platform(self) -> str: ...
    @property
    def target(self) -> str | None: ...
    @property
    def kind(self) -> str: ...

class ObjectFileError(ValueError):
    """Raised when an object file cannot be parsed."""

def parse(
    data: collections.abc.Buffer, *, path: str | os.PathLike[str] | None = None
) -> ObjectFile: ...
def parse_file(path: str | os.PathLike[str]) -> ObjectFile: ...
